### ISSUE TITLE
Install Issues with Linux

### ISSUE THREAD

**Issue by petergault** [Empirical-org-Archive/Documentation#2]
The main issue that started this, was I was unable to log in with "admin@quill.org" password "admin". I was pretty sure the databases had already been seeded. It would be nice to have this process confirmed to work.

After attempting to reseed the database and restart the docker environment, all the commands just hung and I was unable to get the Virtualbox + vagrant + docker + fig env to run properly. 

Now Vagrant seems to timeout for a while, screenshot 1 and 2.

Unfortunately the error messages are not very helpful.

I had been using this google doc to reference when setting up the Compass Module Environment,
https://docs.google.com/a/quill.org/document/d/1wQKBstQbcKeTeQPQoooLpmLrn6Al5pOc77oMN-CDIOc/edit

Now I was told this was the latest, https://github.com/empirical-org/Documentation/blob/master/Getting-Started/Install/Install%20Guide.md

I don't see the instructions anymore for importing docker images in the new markdown version.

I'd like to try to run the dev Compass module environment on my newer linux machine.

It would be nice to include those as well as setting up this environment, or equivalent, for a linux OS as well. Quinn said it is possible with just docker and fig.

When I follow the fig installation for my mac, I get an error. From my knowledge, it looks to be compiled with a different flag than I have. I tried to reach out on Github, https://github.com/orchardup/fig/issues/271, but no response. 

I was able to make something work by using the source code + the `pip` installation, but it is hacky at best. This could be related to my having an older Mac. But having proper linux(Debian/Ubuntu) instructions would resolve this issue for me at least.

![screenshot-2](https://cloud.githubusercontent.com/assets/3667179/3501353/adbfd700-0615-11e4-9450-73c276158bab.png)
![screenshot-1](https://cloud.githubusercontent.com/assets/3667179/3501354/adc5cc32-0615-11e4-902f-18dca27509e2.png)

**Comment by quinn** [comment]
I updated the instructions to include a comment about linux. Everything should be exactly the same except you never run or install the "docker-osx" command.

**Comment by quinn** [comment]
putting on hold until Docker work resumes
